#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UHF.Resource", IsApplication=true)]

namespace UHF
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int arrayAntiQ = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int arrayBank = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int arrayMode = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int arrayPower = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int beep = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int LvTags = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int TvTagCount = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int TvTagLen = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int TvTagRssi = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int TvTagUii = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int btnClear = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int btnGetFre = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int btnGetPower = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int btnGetTime = 2131099676;
			
			// aapt resource value: 0x7f060009
			public const int btnReadData = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int btnScan = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int btnSetFre = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int btnSetPower = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int btnSetTime = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int btnWriteData = 2131099683;
			
			// aapt resource value: 0x7f06000c
			public const int chkAnti = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int edtTxtAddress_R = 2131099653;
			
			// aapt resource value: 0x7f06001f
			public const int edtTxtAddress_W = 2131099679;
			
			// aapt resource value: 0x7f060008
			public const int edtTxtData_R = 2131099656;
			
			// aapt resource value: 0x7f060022
			public const int edtTxtData_W = 2131099682;
			
			// aapt resource value: 0x7f060006
			public const int edtTxtLeng_R = 2131099654;
			
			// aapt resource value: 0x7f060020
			public const int edtTxtLeng_W = 2131099680;
			
			// aapt resource value: 0x7f060007
			public const int edtTxtPassword_R = 2131099655;
			
			// aapt resource value: 0x7f060021
			public const int edtTxtPassword_W = 2131099681;
			
			// aapt resource value: 0x7f06001a
			public const int edtTxtTime = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int edtTxtWait = 2131099675;
			
			// aapt resource value: 0x7f060011
			public const int layout4 = 2131099665;
			
			// aapt resource value: 0x7f060019
			public const int lvR2000 = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int rdoBtn_continuous = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int rdoBtn_singleScan = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int spnBank_R = 2131099652;
			
			// aapt resource value: 0x7f06001e
			public const int spnBank_W = 2131099678;
			
			// aapt resource value: 0x7f060016
			public const int spnPower = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int spnWorkMode = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int sqn_Q = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int tvTotal = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listtag_items = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReadData_Fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Scan_Fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Set_Fragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WriteData_Fragment = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int btnClear = 2130968585;
			
			// aapt resource value: 0x7f040012
			public const int btnGetFre = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int btnGetPower = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int btnGetTime = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int btnReadData = 2130968592;
			
			// aapt resource value: 0x7f040004
			public const int btnScan = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int btnSetFre = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int btnSetPower = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int btnSetTime = 2130968600;
			
			// aapt resource value: 0x7f04001f
			public const int btnWriteData = 2130968607;
			
			// aapt resource value: 0x7f040003
			public const int chkAnti = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int rdoBtn_continuous = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int rdoBtn_singleScan = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int tab_ReadData = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int tab_Scan = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int tab_WriteData = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int tab_set = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int tvAddress = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int tvBank = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int tvData = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int tvLeng = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int tvPassword = 2130968589;
			
			// aapt resource value: 0x7f04001a
			public const int tvPower = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int tvQValues = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int tvTagCount = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int tvTagLen = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int tvTagUii = 2130968604;
			
			// aapt resource value: 0x7f040015
			public const int tvTime = 2130968597;
			
			// aapt resource value: 0x7f04000a
			public const int tvTotal = 2130968586;
			
			// aapt resource value: 0x7f040016
			public const int tvWait = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int tvWorkMode = 2130968601;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
